// Code generated by "lib/js/generate"; DO NOT EDIT.

package js

// Element ...
var Element = &Function{
	Name: "element",
	Definition: `function(selector) {
    const s = functions.selectable(this)
    return s.querySelector(selector)
  }`,
	Dependencies: []*Function{Selectable},
}

// TriggerFavicon ...
var TriggerFavicon = &Function{
	Name: "triggerFavicon",
	Definition: `function() {
    return new Promise((resolve, reject) => {
      const faviconElement = document.querySelector('link[rel~=icon]')
      const href = (faviconElement && faviconElement.href) || '/favicon.ico'
      const faviconUrl = new URL(href, window.location).toString()
      const xhr = new XMLHttpRequest()
      xhr.open('GET', faviconUrl)

      xhr.ontimeout = function () {
        reject({
          errorType: 'timeout_error',
          xhr: xhr
        })
      }

      xhr.onreadystatechange = function () {
        if (xhr.readyState === 4) {
          if ((xhr.status >= 200 && xhr.status < 300) || xhr.status === 304) {
            resolve({
              status: xhr.status,
              statusText: xhr.statusText,
              responseText: xhr.responseText
            })
          } else {
            reject({
              errorType: 'status_error',
              xhr: xhr,
              status: xhr.status,
              statusText: xhr.statusText,
              responseText: xhr.responseText
            })
          }
        }
      }

      xhr.onerror = function () {
        reject({
          errorType: 'onerror',
          xhr: xhr,
          status: xhr.status,
          statusText: xhr.statusText,
          responseText: xhr.responseText
        })
      }
      xhr.send()
    })
  }`,
	Dependencies: []*Function{},
}

// Elements ...
var Elements = &Function{
	Name: "elements",
	Definition: `function(selector) {
    return functions.selectable(this).querySelectorAll(selector)
  }`,
	Dependencies: []*Function{Selectable},
}

// ElementX ...
var ElementX = &Function{
	Name: "elementX",
	Definition: `function(xPath) {
    const s = functions.selectable(this)
    return document.evaluate(
      xPath,
      s,
      null,
      XPathResult.FIRST_ORDERED_NODE_TYPE
    ).singleNodeValue
  }`,
	Dependencies: []*Function{Selectable},
}

// ElementsX ...
var ElementsX = &Function{
	Name: "elementsX",
	Definition: `function(xpath) {
    const s = functions.selectable(this)
    const iter = document.evaluate(
      xpath,
      s,
      null,
      XPathResult.ORDERED_NODE_ITERATOR_TYPE
    )
    const list = []
    let el
    while ((el = iter.iterateNext())) list.push(el)
    return list
  }`,
	Dependencies: []*Function{Selectable},
}

// ElementR ...
var ElementR = &Function{
	Name: "elementR",
	Definition: `function(selector, regex) {
    let reg
    const m = regex.match(/(\/?)(.+)\1([a-z]*)/i)
    // cSpell:ignore gmix
    if (!m || (m[3] && !/^(?!.*?(.).*?\1)[gmixXsuUAJ]+$/.test(m[3])))
      reg = new RegExp(regex)
    else reg = new RegExp(m[2], m[3])

    const s = functions.selectable(this)
    const el = Array.from(s.querySelectorAll(selector)).find((e) =>
      reg.test(functions.text.call(e))
    )
    return el ? el : null
  }`,
	Dependencies: []*Function{Selectable, Text},
}

// Parents ...
var Parents = &Function{
	Name: "parents",
	Definition: `function(selector) {
    let p = this.parentElement
    const list = []
    while (p) {
      if (p.matches(selector)) {
        list.push(p)
      }
      p = p.parentElement
    }
    return list
  }`,
	Dependencies: []*Function{},
}

// ContainsElement ...
var ContainsElement = &Function{
	Name: "containsElement",
	Definition: `function(target) {
    let node = target
    while (node != null) {
      if (node === this) {
        return true
      }
      node = node.parentElement
    }
    return false
  }`,
	Dependencies: []*Function{},
}

// InitMouseTracer ...
var InitMouseTracer = &Function{
	Name: "initMouseTracer",
	Definition: `async function(iconId, icon) {
    await functions.waitLoad()

    if (document.getElementById(iconId)) {
      return
    }

    const tmp = document.createElement('div')
    tmp.innerHTML = icon
    const svg = tmp.lastChild
    svg.id = iconId
    svg.style =
      'position: absolute; z-index: 2147483647; width: 17px; pointer-events: none;'
    svg.removeAttribute('width')
    svg.removeAttribute('height')
    document.body.parentElement.appendChild(svg)
  }`,
	Dependencies: []*Function{WaitLoad},
}

// UpdateMouseTracer ...
var UpdateMouseTracer = &Function{
	Name: "updateMouseTracer",
	Definition: `function(iconId, x, y) {
    const svg = document.getElementById(iconId)
    if (!svg) {
      return false
    }
    svg.style.left = x - 2 + 'px'
    svg.style.top = y - 3 + 'px'
    return true
  }`,
	Dependencies: []*Function{},
}

// Rect ...
var Rect = &Function{
	Name: "rect",
	Definition: `function() {
    const b = functions.tag(this).getBoundingClientRect()
    return { x: b.x, y: b.y, width: b.width, height: b.height }
  }`,
	Dependencies: []*Function{Tag},
}

// Overlay ...
var Overlay = &Function{
	Name: "overlay",
	Definition: `async function(id, left, top, width, height, msg, monospace) {
    await functions.waitLoad()

    const div = document.createElement('div')
    div.id = id
    div.style = ` + "`" + `position: fixed; z-index:2147483647; border: 2px dashed red;
        border-radius: 3px; box-shadow: #5f3232 0 0 3px; pointer-events: none;
        box-sizing: border-box;
        left: ${left}px;
        top: ${top}px;
        height: ${height}px;
        width: ${width}px;` + "`" + `

    if (width * height === 0) {
      div.style.border = 'none'
    }

    if (!msg) {
      document.body.parentElement.appendChild(div)
      return
    }

    const msgDiv = document.createElement('div')
    msgDiv.style = ` + "`" + `position: absolute; color: #cc26d6; font-size: 12px; background: #ffffffeb;
        box-shadow: #333 0 0 3px; padding: 2px 5px; border-radius: 3px; white-space: nowrap;
        top: ${height}px;` + "`" + `

    // Messages can contain page-controlled or typed text, so never parse them as HTML.
    msgDiv.textContent = msg
    if (monospace) msgDiv.style.fontFamily = 'monospace'
    div.appendChild(msgDiv)
    document.body.parentElement.appendChild(div)

    if (window.innerHeight < msgDiv.offsetHeight + top + height) {
      msgDiv.style.top = -msgDiv.offsetHeight - 2 + 'px'
    }

    if (window.innerWidth < msgDiv.offsetWidth + left) {
      msgDiv.style.left = window.innerWidth - msgDiv.offsetWidth - left + 'px'
    }
  }`,
	Dependencies: []*Function{WaitLoad},
}

// ElementOverlay ...
var ElementOverlay = &Function{
	Name: "elementOverlay",
	Definition: `async function(id, msg) {
    const interval = 100
    const el = functions.tag(this)

    let pre = el.getBoundingClientRect()
    await functions.overlay(id, pre.left, pre.top, pre.width, pre.height, msg)

    const update = () => {
      const overlay = document.getElementById(id)
      if (overlay === null) return

      const box = el.getBoundingClientRect()
      if (
        pre.left === box.left &&
        pre.top === box.top &&
        pre.width === box.width &&
        pre.height === box.height
      ) {
        setTimeout(update, interval)
        return
      }

      overlay.style.left = box.left + 'px'
      overlay.style.top = box.top + 'px'
      overlay.style.width = box.width + 'px'
      overlay.style.height = box.height + 'px'
      pre = box

      setTimeout(update, interval)
    }

    setTimeout(update, interval)
  }`,
	Dependencies: []*Function{Tag, Overlay},
}

// RemoveOverlay ...
var RemoveOverlay = &Function{
	Name: "removeOverlay",
	Definition: `function(id) {
    const el = document.getElementById(id)
    // prevent override like prototype.js
    el && Element.prototype.remove.call(el)
  }`,
	Dependencies: []*Function{},
}

// WaitIdle ...
var WaitIdle = &Function{
	Name: "waitIdle",
	Definition: `function(timeout) {
    return new Promise((resolve) => {
      window.requestIdleCallback(resolve, { timeout })
    })
  }`,
	Dependencies: []*Function{},
}

// WaitInteractive ...
var WaitInteractive = &Function{
	Name: "waitInteractive",
	Definition: `function() {
    return document.readyState === 'interactive' || document.readyState === 'complete'
  }`,
	Dependencies: []*Function{},
}

// WaitLoad ...
var WaitLoad = &Function{
	Name: "waitLoad",
	Definition: `function() {
    const isWin = this === window
    return new Promise((resolve, reject) => {
      if (isWin) {
        if (document.readyState === 'complete') return resolve()
        window.addEventListener('load', () => resolve(), { once: true })
      } else {
        if (this.complete === undefined || this.complete) {
          resolve()
        } else {
          const cleanup = () => {
            this.removeEventListener('load', loaded)
            this.removeEventListener('error', failed)
          }
          const loaded = () => {
            cleanup()
            resolve()
          }
          const failed = () => {
            cleanup()
            reject(new Error('Resource failed to load'))
          }
          this.addEventListener('load', loaded)
          this.addEventListener('error', failed)
        }
      }
    })
  }`,
	Dependencies: []*Function{},
}

// SetFilesFromMemory ...
var SetFilesFromMemory = &Function{
	Name: "setFilesFromMemory",
	Definition: `function(files) {
    const win = this.ownerDocument.defaultView
    if (!(this instanceof win.HTMLInputElement) || this.type !== 'file') {
      throw new Error('element is not an input[type=file]')
    }
    files = files || []
    if (!this.multiple && files.length > 1) {
      throw new Error('multiple files require an input with multiple enabled')
    }

    const transfer = new win.DataTransfer()
    for (const file of files) {
      // Go's JSON encoding transfers []byte as base64; nil represents an empty file.
      const binary = win.atob(file.data || '')
      const bytes = new win.Uint8Array(binary.length)
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
      transfer.items.add(new win.File([bytes], file.name, { type: file.mimeType }))
    }
    this.files = transfer.files
    this.dispatchEvent(new win.Event('input', { bubbles: true, composed: true }))
    this.dispatchEvent(new win.Event('change', { bubbles: true }))
  }`,
	Dependencies: []*Function{},
}

// InputEvent ...
var InputEvent = &Function{
	Name: "inputEvent",
	Definition: `function() {
    this.dispatchEvent(new Event('input', { bubbles: true }))
    this.dispatchEvent(new Event('change', { bubbles: true }))
  }`,
	Dependencies: []*Function{},
}

// InputTime ...
var InputTime = &Function{
	Name: "inputTime",
	Definition: `function(stamp) {
    const time = new Date(stamp)

    const pad = (n) => n.toString().padStart(2, '0')

    const y = time.getFullYear()
    const mon = pad(time.getMonth() + 1)
    const d = pad(time.getDate())
    const h = pad(time.getHours())
    const min = pad(time.getMinutes())

    switch (this.type) {
      case 'date':
        this.value = ` + "`" + `${y}-${mon}-${d}` + "`" + `
        break
      case 'datetime-local':
        this.value = ` + "`" + `${y}-${mon}-${d}T${h}:${min}` + "`" + `
        break
      case 'month':
        this.value = ` + "`" + `${y}-${mon}` + "`" + `
        break
      case 'time':
        this.value = ` + "`" + `${h}:${min}` + "`" + `
        break
    }

    functions.inputEvent.call(this)
  }`,
	Dependencies: []*Function{InputEvent},
}

// InputColor ...
var InputColor = &Function{
	Name: "inputColor",
	Definition: `function(color) {
    this.value = ` + "`" + `${color}` + "`" + `

    functions.inputEvent.call(this)
  }`,
	Dependencies: []*Function{InputEvent},
}

// SelectText ...
var SelectText = &Function{
	Name: "selectText",
	Definition: `function(pattern) {
    const m = this.value.match(new RegExp(pattern))
    if (m) {
      this.setSelectionRange(m.index, m.index + m[0].length)
    }
  }`,
	Dependencies: []*Function{},
}

// SelectAllText ...
var SelectAllText = &Function{
	Name: "selectAllText",
	Definition: `function() {
    this.select()
  }`,
	Dependencies: []*Function{},
}

// Select ...
var Select = &Function{
	Name: "select",
	Definition: `function(selectors, selected, type) {
    let matchers
    switch (type) {
      case 'regex':
        matchers = selectors.map((s) => {
          const reg = new RegExp(s)
          return (el) => reg.test(el.innerText)
        })
        break
      case 'css-selector':
        matchers = selectors.map((s) => (el) => el.matches(s))
        break
      default:
        matchers = selectors.map((s) => (el) => el.innerText.includes(s))
        break
    }

    const opts = Array.from(this.options)
    let has = false
    matchers.forEach((s) => {
      const el = opts.find(s)
      if (el) {
        el.selected = selected
        has = true
        return
      }
    })

    this.dispatchEvent(new Event('input', { bubbles: true }))
    this.dispatchEvent(new Event('change', { bubbles: true }))

    return has
  }`,
	Dependencies: []*Function{},
}

// Visible ...
var Visible = &Function{
	Name: "visible",
	Definition: `function() {
    const el = functions.tag(this)
    const box = el.getBoundingClientRect()
    const style = window.getComputedStyle(el)
    return (
      style.display !== 'none' &&
      style.visibility !== 'hidden' &&
      !!(box.top || box.bottom || box.width || box.height)
    )
  }`,
	Dependencies: []*Function{Tag},
}

// Invisible ...
var Invisible = &Function{
	Name: "invisible",
	Definition: `function() {
    return !functions.visible.apply(this)
  }`,
	Dependencies: []*Function{Visible},
}

// Text ...
var Text = &Function{
	Name: "text",
	Definition: `function() {
    switch (this.tagName) {
      case 'INPUT':
      case 'TEXTAREA':
        return this.value || this.placeholder
      case 'SELECT':
        return Array.from(this.selectedOptions)
          .map((el) => el.innerText)
          .join()
      case undefined:
        return this.textContent
      default:
        return this.innerText
    }
  }`,
	Dependencies: []*Function{},
}

// Resource ...
var Resource = &Function{
	Name: "resource",
	Definition: `function() {
    return new Promise((resolve, reject) => {
      if (this.complete) {
        return resolve(this.currentSrc)
      }
      this.addEventListener('load', () => resolve(this.currentSrc))
      this.addEventListener('error', (e) => reject(e))
    })
  }`,
	Dependencies: []*Function{},
}

// AddScriptTag ...
var AddScriptTag = &Function{
	Name: "addScriptTag",
	Definition: `function(id, url, content) {
    if (document.getElementById(id)) return

    return new Promise((resolve, reject) => {
      const s = document.createElement('script')

      if (url) {
        s.src = url
        s.onload = resolve
      } else {
        s.type = 'text/javascript'
        s.text = content
        resolve()
      }

      s.id = id
      s.onerror = reject
      document.head.appendChild(s)
    })
  }`,
	Dependencies: []*Function{},
}

// AddStyleTag ...
var AddStyleTag = &Function{
	Name: "addStyleTag",
	Definition: `function(id, url, content) {
    if (document.getElementById(id)) return

    return new Promise((resolve, reject) => {
      let el

      if (url) {
        el = document.createElement('link')
        el.rel = 'stylesheet'
        el.href = url
      } else {
        el = document.createElement('style')
        el.type = 'text/css'
        el.appendChild(document.createTextNode(content))
        resolve()
      }

      el.id = id
      el.onload = resolve
      el.onerror = reject
      document.head.appendChild(el)
    })
  }`,
	Dependencies: []*Function{},
}

// Selectable ...
var Selectable = &Function{
	Name: "selectable",
	Definition: `function(s) {
    return s.querySelector ? s : document
  }`,
	Dependencies: []*Function{},
}

// Tag ...
var Tag = &Function{
	Name: "tag",
	Definition: `function(el) {
    return el.tagName ? el : el.parentElement
  }`,
	Dependencies: []*Function{},
}

// ExposeFunc ...
var ExposeFunc = &Function{
	Name: "exposeFunc",
	Definition: `function(name, bind) {
    let callbackCount = 0
    window[name] = (req) =>
      new Promise((resolve, reject) => {
        const cb = bind + '_cb' + callbackCount++
        window[cb] = (res, err) => {
          delete window[cb]
          err ? reject(err) : resolve(res)
        }
        window[bind](JSON.stringify({ req, cb }))
      })
  }`,
	Dependencies: []*Function{},
}

// GetXPath ...
var GetXPath = &Function{
	Name: "getXPath",
	Definition: `function(optimized) {
    class Step {
      constructor(value, optimized) {
        this.value = value
        this.optimized = optimized || false
      }
      toString() {
        return this.value
      }
    }
    const xPathValue = function xPathValue(node, optimized) {
      let ownValue
      const ownIndex = xPathIndex(node)
      if (ownIndex === -1) {
        return null
      }
      switch (node.nodeType) {
        case Node.ELEMENT_NODE:
          if (optimized && node.id) {
            // Use the structural path when neither XPath quote delimiter is safe.
            if (!node.id.includes("'")) return new Step(` + "`" + `//*[@id='${node.id}']` + "`" + `, true)
            if (!node.id.includes('"')) return new Step(` + "`" + `//*[@id="${node.id}"]` + "`" + `, true)
          }
          ownValue = node.localName
          break
        case Node.ATTRIBUTE_NODE:
          ownValue = ` + "`" + `@${node.nodeName}` + "`" + `
          break
        case Node.TEXT_NODE:
        case Node.CDATA_SECTION_NODE:
          ownValue = 'text()'
          break
        case Node.PROCESSING_INSTRUCTION_NODE:
          ownValue = 'processing-instruction()'
          break
        case Node.COMMENT_NODE:
          ownValue = 'comment()'
          break
        case Node.DOCUMENT_NODE:
          ownValue = ''
          break
        default:
          ownValue = ''
          break
      }
      if (ownIndex > 0) {
        ownValue += ` + "`" + `[${ownIndex}]` + "`" + `
      }
      return new Step(ownValue, node.nodeType === Node.DOCUMENT_NODE)
    }
    const xPathIndex = function xPathIndex(node) {
      function areNodesSimilar(left, right) {
        if (left === right) {
          return true
        }
        if (
          left.nodeType === Node.ELEMENT_NODE &&
          right.nodeType === Node.ELEMENT_NODE
        ) {
          return left.localName === right.localName
        }
        if (left.nodeType === right.nodeType) {
          return true
        }
        const leftType =
          left.nodeType === Node.CDATA_SECTION_NODE
            ? Node.TEXT_NODE
            : left.nodeType
        const rightType =
          right.nodeType === Node.CDATA_SECTION_NODE
            ? Node.TEXT_NODE
            : right.nodeType
        return leftType === rightType
      }
      const parentNode = node.parentNode
      const siblings = parentNode ? parentNode.children : null
      if (!siblings) {
        return 0
      }
      let hasSameNamedElements
      for (let i = 0; i < siblings.length; ++i) {
        if (areNodesSimilar(node, siblings[i]) && !(siblings[i] === node)) {
          hasSameNamedElements = true
          break
        }
      }
      if (!hasSameNamedElements) {
        return 0
      }
      let ownIndex = 1
      for (let i = 0; i < siblings.length; ++i) {
        if (areNodesSimilar(node, siblings[i])) {
          if (siblings[i] === node) {
            return ownIndex
          }
          ++ownIndex
        }
      }
      return -1
    }
    const node = this
    if (node.nodeType === Node.DOCUMENT_NODE) {
      return '/'
    }
    const steps = []
    let contextNode = node
    while (contextNode) {
      const step = xPathValue(contextNode, optimized)
      if (!step) {
        break
      }
      steps.push(step)
      if (step.optimized) {
        break
      }
      contextNode = contextNode.parentNode
    }
    steps.reverse()
    return (steps.length && steps[0].optimized ? '' : '/') + steps.join('/')
  }`,
	Dependencies: []*Function{},
}

// WaitDOMStable ...
var WaitDOMStable = &Function{
	Name: "waitDOMStable",
	Definition: `function(ms, diff) {
    // Checks are due at most slice milliseconds apart. A waiter whose check
    // is overdue by grace milliseconds ends itself, so a caller that lost the
    // connection leaves nothing behind.
    const slice = 60000
    const grace = 10000
    const options = {
      subtree: true,
      childList: true,
      attributes: true,
      attributeOldValue: true,
      characterData: true,
      characterDataOldValue: true
    }
    const counting = diff > 0
    const nodes = counting ? NodeFilter.SHOW_ALL : NodeFilter.SHOW_ELEMENT
    const roots = new WeakSet()
    let changed = counting ? new Set() : null
    let dirty = false
    let limit = 0
    let start = 0
    let found = 0
    let timer = 0
    let status = ''
    let observer = null
    // The digest at the previous check while the page cannot run callbacks.
    let last

    const change = (node) => {
      dirty = true
      if (changed) changed.add(node)
    }
    // Visits root and its descendants of the kinds in what, including open
    // shadow trees, and returns their number. With mark, it counts each
    // visited node as changed. With watch, it observes the shadow roots not
    // yet observed and adds their number to found.
    const visit = (root, what, mark, watch) => {
      let count = 0
      const stack = [root]
      while (stack.length) {
        const walker = document.createTreeWalker(stack.pop(), what)
        for (let n = walker.currentNode; n; n = walker.nextNode()) {
          count++
          if (mark) change(n)
          const shadow = n.shadowRoot
          if (!shadow) continue
          if (watch && !roots.has(shadow)) {
            roots.add(shadow)
            observer.observe(shadow, options)
            found++
          }
          stack.push(shadow)
        }
      }
      return count
    }
    const restart = () => {
      start = performance.now()
      if (changed) changed = new Set()
    }
    // Reports whether the page runs callbacks, which deliver the observer's
    // records.
    const live = () => {
      let ran = false
      const target = new EventTarget()
      target.addEventListener('check', () => {
        ran = true
      })
      target.dispatchEvent(new Event('check'))
      return ran
    }
    // Returns a hash of the document and its open shadow trees: their
    // structure, node names, attributes, and character data.
    const digest = () => {
      let hash = 0x811c9dc5
      const add = (code) => {
        hash = Math.imul(hash ^ code, 16777619)
      }
      const mix = (value) => {
        for (let i = 0; i < value.length; i++) add(value.charCodeAt(i))
        add(0x10000)
      }
      const stack = [document]
      while (stack.length) {
        const root = stack.pop()
        for (let n = root; n; ) {
          add(n.nodeType)
          if (n.nodeType === Node.ELEMENT_NODE) {
            mix(n.localName)
            for (const name of n.getAttributeNames()) {
              mix(name)
              mix(n.getAttribute(name))
            }
            if (n.shadowRoot) stack.push(n.shadowRoot)
          } else if (typeof n.data === 'string') {
            mix(n.data)
          }
          // Visit the nodes in tree order, marking each descent and ascent.
          if (n.firstChild) {
            add(0x10001)
            n = n.firstChild
            continue
          }
          while (n !== root && !n.nextSibling) {
            add(0x10002)
            n = n.parentNode
          }
          n = n === root ? null : n.nextSibling
        }
      }
      return hash
    }
    // Compares digests while the page cannot run callbacks. A digest that
    // differs from the previous check, or callbacks that stopped since then,
    // restart the period.
    const compare = () => {
      const running = live()
      if (running && last === undefined) return
      const hash = digest()
      if (hash !== last) restart()
      last = running ? undefined : hash
    }
    // Counts the net effect of a batch of records. A node inserted and
    // removed again, and an attribute or text restored to its value before
    // the batch, are not changes. A change beyond the limit restarts the
    // stability period.
    const handle = (records) => {
      const added = new Set()
      const values = new Map()
      const before = (target, key, value) => {
        let entry = values.get(target)
        if (!entry) values.set(target, (entry = new Map()))
        if (!entry.has(key)) entry.set(key, value)
      }
      for (const record of records) {
        const target = record.target
        if (record.type === 'childList') {
          for (const node of record.addedNodes) added.add(node)
          if (!target.isConnected) continue
          for (const node of record.removedNodes) {
            if (added.has(node)) continue
            if (counting) visit(node, nodes, true, false)
            else dirty = true
          }
        } else if (record.type === 'attributes') {
          const ns = record.attributeNamespace
          const name = record.attributeName
          before(target, ns + ' ' + name, [ns, name, record.oldValue])
        } else {
          before(target, '', [null, null, record.oldValue])
        }
      }
      for (const node of added) {
        if (node.isConnected) visit(node, nodes, true, true)
      }
      for (const [target, entry] of values) {
        if (!target.isConnected) continue
        for (const [key, [ns, name, value]] of entry) {
          if (value !== (key ? target.getAttributeNS(ns, name) : target.data)) {
            change(target)
          }
        }
      }
      if (!dirty) return
      dirty = false
      if (!changed || changed.size > limit) restart()
    }
    const settle = (value) => {
      if (!status) {
        status = value
        if (observer) observer.disconnect()
        clearTimeout(timer)
        window.removeEventListener('pagehide', hidden)
        changed = null
      }
      return status
    }
    const hidden = () => settle('hidden')
    const expire = () => settle('expired')
    // Returns the milliseconds until the next check and renews the timer
    // that ends an abandoned waiter.
    const next = (now) => {
      const wait = Math.min(Math.max(Math.ceil(start + ms - now), 1), slice)
      clearTimeout(timer)
      timer = setTimeout(expire, wait + grace)
      return wait
    }
    const guard = (fn) => {
      if (status) return status
      try {
        return fn()
      } catch (error) {
        settle('failed')
        throw error
      }
    }

    return {
      start() {
        return guard(() => {
          if (observer) return next(performance.now())
          observer = new MutationObserver(handle)
          window.addEventListener('pagehide', hidden)
          observer.observe(document, options)
          limit = diff * visit(document, nodes, false, true)
          if (!live()) last = digest()
          start = performance.now()
          return next(start)
        })
      },
      check() {
        return guard(() => {
          handle(observer.takeRecords())
          compare()
          const now = performance.now()
          if (now - start < ms) return next(now)
          // A shadow root attached to an element already in the document was
          // not observed during the period.
          found = 0
          visit(document, NodeFilter.SHOW_ELEMENT, false, true)
          if (!found) return settle('stable')
          restart()
          return next(start)
        })
      },
      cancel() {
        return settle('canceled')
      }
    }
  }`,
	Dependencies: []*Function{},
}
