// Code generated by "lib/proto/generate"; DO NOT EDIT.
// Schema SHA-256: 2baa96e91c764182a6ee5ff4048d744082a34ef786aa0e3ac9c7bfe2ce9bc625

package proto

/*

CrashReportContext

This domain exposes the current state of the CrashReportContext API.

*/

// CrashReportContextCrashReportContextEntry Key-value pair in CrashReportContext.
type CrashReportContextCrashReportContextEntry struct {
	// Key ...
	Key string `json:"key"`

	// Value ...
	Value string `json:"value"`

	// FrameID The ID of the frame where the key-value pair was set.
	FrameID PageFrameID `json:"frameId"`
}

// CrashReportContextGetEntries Returns all entries in the CrashReportContext across all frames in the page.
type CrashReportContextGetEntries struct{}

// ProtoReq name.
func (m CrashReportContextGetEntries) ProtoReq() string { return "CrashReportContext.getEntries" }

// Call sends the request.
func (m CrashReportContextGetEntries) Call(c Client) (*CrashReportContextGetEntriesResult, error) {
	var res CrashReportContextGetEntriesResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// CrashReportContextGetEntriesResult ...
type CrashReportContextGetEntriesResult struct {
	// Entries ...
	Entries []*CrashReportContextCrashReportContextEntry `json:"entries"`
}
