// Code generated by "lib/proto/generate"; DO NOT EDIT.
// Schema SHA-256: 3c7f00438bbe5203d820a4e215f1fff12a0ce85766f97e6901c52fa17b638bd7

package proto

/*

Schema

This domain is deprecated.

*/

// SchemaDomain Description of the protocol domain.
type SchemaDomain struct {
	// Name Domain name.
	Name string `json:"name"`

	// Version Domain version.
	Version string `json:"version"`
}

// SchemaGetDomains Returns supported domains.
type SchemaGetDomains struct{}

// ProtoReq name.
func (m SchemaGetDomains) ProtoReq() string { return "Schema.getDomains" }

// Call sends the request.
func (m SchemaGetDomains) Call(c Client) (*SchemaGetDomainsResult, error) {
	var res SchemaGetDomainsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// SchemaGetDomainsResult ...
type SchemaGetDomainsResult struct {
	// Domains List of supported domains.
	Domains []*SchemaDomain `json:"domains"`
}
