// Code generated by "lib/proto/generate"; DO NOT EDIT.
// Schema SHA-256: 2baa96e91c764182a6ee5ff4048d744082a34ef786aa0e3ac9c7bfe2ce9bc625

package proto

/*

Schema

This domain is deprecated.

*/

// SchemaDomain Description of the protocol domain.
type SchemaDomain struct {
	// Name Domain name.
	Name string `json:"name"`

	// Version Domain version.
	Version string `json:"version"`
}

// SchemaGetDomains Returns supported domains.
type SchemaGetDomains struct{}

// ProtoReq name.
func (m SchemaGetDomains) ProtoReq() string { return "Schema.getDomains" }

// Call sends the request.
func (m SchemaGetDomains) Call(c Client) (*SchemaGetDomainsResult, error) {
	var res SchemaGetDomainsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// SchemaGetDomainsResult ...
type SchemaGetDomainsResult struct {
	// Domains List of supported domains.
	Domains []*SchemaDomain `json:"domains"`
}
