// Package main ...
package main

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/rah-0/rod/lib/jsonvalue"
	"github.com/rah-0/rod/lib/utils"
)

const (
	deviceListURL = "https://raw.githubusercontent.com/ChromeDevTools/devtools-frontend/c4e2fefe3327aa9fe5f4398a1baddb8726c230d5/front_end/emulated_devices/module.json"
	deviceListSHA = "c22caf7ea110abb68a712ab240cff2efec8e804c7492ec73ff157875d4006e27"
	chromeVersion = "114.0.0.0"
)

func main() {
	source := flag.String("source", "lib/devices/generate/devices.json", "pinned device JSON snapshot")
	output := flag.String("out", "lib/devices/list.go", "generated output file")
	flag.Parse()
	if err := generate(*source, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(source, output string) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	if fmt.Sprintf("%x", sha256.Sum256(data)) != deviceListSHA {
		return fmt.Errorf("device list checksum mismatch")
	}
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	code, err := render(jsonvalue.New(value).Get("extensions"))
	if err != nil {
		return err
	}
	return writeOutput(output, code)
}

func render(devices jsonvalue.Value) ([]byte, error) {
	var code strings.Builder
	for _, d := range devices.Arr() {
		d = d.Get("device")
		name := d.Get("title").String()

		code.WriteString(utils.S(`

			// {{.name}} device.
			{{.name}} = Device{
				Title:        "{{.title}}",
				Capabilities: {{.capabilities}},
				UserAgent:    "{{.userAgent}}",
				AcceptLanguage: "en",
				Screen: Screen{
					DevicePixelRatio: {{.devicePixelRatio}},
					Horizontal: ScreenSize{
						Width: {{.horizontalWidth}},
						Height: {{.horizontalHeight}},
					},
					Vertical: ScreenSize{
						Width: {{.verticalWidth}},
						Height: {{.verticalHeight}},
					},
				},
			}`,
			"name", normalizeName(name),
			"title", name,
			"capabilities", toGoArr(d.Get("capabilities")),
			"userAgent", getUserAgent(d),
			"devicePixelRatio", d.Get("screen.device-pixel-ratio").Int(),
			"horizontalWidth", d.Get("screen.horizontal.width").Int(),
			"horizontalHeight", d.Get("screen.horizontal.height").Int(),
			"verticalWidth", d.Get("screen.vertical.width").Int(),
			"verticalHeight", d.Get("screen.vertical.height").Int(),
		))
	}

	source := utils.S(`// Code generated by "lib/devices/generate"; DO NOT EDIT.
// Source: {{.source}}
// SHA-256: {{.sha}}
// Chrome user-agent version: {{.version}}

package devices

var (
 {{.code}}
)
`, "code", code.String(), "source", deviceListURL, "sha", deviceListSHA, "version", chromeVersion)
	return format.Source([]byte(source))
}

func writeOutput(path string, data []byte) (err error) {
	file, err := os.CreateTemp(filepath.Dir(path), ".devices-generate-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err := file.Write(data); err != nil {
		file.Close()
		return err
	}
	if err := file.Chmod(0o644); err != nil {
		file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), path)
}

func normalizeName(name string) string {
	name = strings.ReplaceAll(name, "/", "or")

	list := []string{}
	for s := range strings.SplitSeq(name, " ") {
		if len(s) > 1 {
			list = append(list, strings.ToUpper(s[0:1])+s[1:])
		} else {
			list = append(list, strings.ToUpper(s))
		}
	}

	return strings.Join(list, "")
}

func getUserAgent(val jsonvalue.Value) string {
	ua := val.Get("user-agent").String()
	if ua == "" {
		return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/" + chromeVersion + " Safari/537.36"
	}
	ua = strings.ReplaceAll(ua, "%s", chromeVersion)
	return ua
}

func toGoArr(val jsonvalue.Value) string {
	list := []string{}
	for _, s := range val.Arr() {
		list = append(list, s.String())
	}
	return fmt.Sprintf("%#v", list)
}
