// Package main ...
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/doc/comment"
	"go/format"
	"os"
	"os/signal"
	"regexp"
	"strings"
	"syscall"
	"time"

	"github.com/rah-0/rod/lib/defaults"
	"github.com/rah-0/rod/lib/jsonvalue"
	"github.com/rah-0/rod/lib/utils"
)

const generatedHeader = "// Code generated by \"lib/proto/generate\"; DO NOT EDIT."

func main() {
	var options GeneratorOptions
	flag.StringVar(&options.SchemaPath, "schema", "", "explicit offline protocol JSON input; default: installed browser")
	flag.StringVar(&options.CompatPath, "compat", "", "protocol JSON of an older browser; record the members it lacks as optional in older browsers")
	flag.StringVar(&options.OutputDir, "out", "lib/proto", "generated output directory")
	flag.StringVar(&options.Bin, "bin", "", "browser executable; default: configured or installed browser")
	flag.BoolVar(&options.NoSandbox, "no-sandbox", false, "explicitly disable the browser sandbox")
	flag.BoolVar(&options.Check, "check", false, "report stale generated bindings without writing files")
	flag.DurationVar(&options.Timeout, "timeout", 30*time.Second, "browser startup and protocol capture timeout")
	defaults.Load()
	flag.Parse()
	// Protocol capture always owns a fresh profile, including its guardian cleanup.
	defaults.Dir = ""
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	err := generate(ctx, options, os.Stdout)
	stop()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// render returns the generated files for the schema data. The compatibility
// record starts from compat and adds the members that each older schema lacks.
func render(data []byte, compat compatibility, older ...[]byte) (files map[string][]byte, err error) {
	// Invalid references and missing patch targets are schema errors, not partial output.
	defer func() {
		if failure := recover(); failure != nil {
			files = nil
			err = fmt.Errorf("invalid protocol schema: %v", failure)
		}
	}()
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return nil, err
	}
	data, err = normalizeSchema(data)
	if err != nil {
		return nil, err
	}
	schema := jsonvalue.New(value)
	if schema.Get("version.major").Str() == "" || schema.Get("version.minor").Str() == "" || len(schema.Get("domains").Arr()) == 0 {
		return nil, fmt.Errorf("protocol schema must contain a version and domains")
	}
	header := generatedHeader + fmt.Sprintf("\n// Schema SHA-256: %x\n\n", sha256.Sum256(data))
	var registry, tests, decoding strings.Builder
	registry.WriteString(header)
	registry.WriteString(utils.S(`package proto

import "reflect"

// Version of cdp protocol.
const Version = "v{{.major}}.{{.minor}}"

var types = map[string]reflect.Type{
`, "major", schema.Get("version.major").Str(), "minor", schema.Get("version.minor").Str()))
	decoding.WriteString(header + "package proto\n")
	files = map[string][]byte{"definitions.go": nil, "definitions_test.go": nil, decodersOutput: nil}
	domains := parse(schema)
	compat, err = compat.update(domains, older...)
	if err != nil {
		return nil, err
	}
	decoders := newDecoders(domains, compat.set())
	for _, domain := range domains {
		var body strings.Builder
		fmt.Fprintf(&body, "/*\n\n%s\n\n", domain.name)
		if domain.description != "" {
			body.WriteString(domain.description + "\n\n")
		}
		body.WriteString("*/\n\n")
		for _, definition := range domain.definitions {
			if definition.skip {
				continue
			}
			body.WriteString(definition.format())
			decoding.WriteString(decoders.format(definition))
			tests.WriteString(definition.formatTests(decoders))
			if definition.originName != "" {
				fmt.Fprintf(&registry, "%q: reflect.TypeFor[%s](),\n", domain.name+"."+definition.originName, definition.name)
			}
		}
		var code strings.Builder
		code.WriteString(header + "package proto\n")
		if strings.Contains(body.String(), "jsonvalue.") {
			code.WriteString("\nimport \"github.com/rah-0/rod/lib/jsonvalue\"\n")
		}
		code.WriteString("\n" + body.String())
		name := toSnakeCase(domain.name) + ".go"
		if _, duplicate := files[name]; duplicate {
			return nil, fmt.Errorf("duplicate output %q", name)
		}
		files[name] = []byte(code.String())
	}
	registry.WriteString("}\n")
	files["definitions.go"] = []byte(registry.String())
	imports := "\"reflect\"\n\"testing\"\n"
	if strings.Contains(tests.String(), "json.RawMessage") {
		imports = "\"encoding/json\"\n" + imports
	}
	files["definitions_test.go"] = []byte(header + "package proto_test\n\nimport (\n" + imports +
		"\n\"github.com/rah-0/rod/lib/proto\"\n)\n" + tests.String())
	code := decoding.String()
	if strings.Contains(code, "jsonvalue.") {
		code = strings.Replace(code, "package proto\n", "package proto\n\nimport \"github.com/rah-0/rod/lib/jsonvalue\"\n", 1)
	}
	files[decodersOutput] = []byte(code)
	for name, code := range files {
		code = regexp.MustCompile(`struct \{\s*}`).ReplaceAll(code, []byte("struct{}"))
		formatted, err := format.Source(code)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
		code = bytes.ReplaceAll(formatted, []byte("struct {\n\n"), []byte("struct {\n"))
		// Reparse at the normalized positions so gofmt also formats doc comments
		// whose first lines were indented by the templates.
		files[name], err = format.Source(code)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
	}
	files[compatibilityOutput] = compat.encode()
	return files, nil
}

func (d *definition) comment() string {
	text := d.description
	if text == "enum" {
		text = "enum."
	}

	if text == "<nil>" {
		text = "..."
	}

	if d.older {
		text = "(optional in older browsers) " + text
	}
	if d.optional {
		text = "(optional) " + text
	}
	if d.experimental {
		text = "(experimental) " + text
	}

	name := symbol(d.name)

	if !strings.HasPrefix(strings.TrimSpace(text), name) {
		text = name + " " + text
	}

	if d.deprecated {
		text += "\n\nDeprecated: This protocol API is deprecated."
	}
	// Normalize schema indentation before templates add their own indentation.
	// Otherwise gofmt can need another pass to recognize indented comment blocks.
	var parser comment.Parser
	var printer comment.Printer
	text = strings.TrimSuffix(string(printer.Comment(parser.Parse(text))), "\n")
	var out strings.Builder
	for line := range strings.SplitSeq(text, "\n") {
		out.WriteString("//")
		if line != "" && !strings.HasPrefix(line, "\t") {
			out.WriteByte(' ')
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return strings.TrimSuffix(out.String(), "\n")
}

func (d *definition) format() (code string) {
	switch d.objType {
	case objTypePrimitive:
		code = utils.S(`
		{{.comment}}
		type {{.name}} {{.type}}
		`, "name", d.name, "type", d.typeName, "comment", d.comment())

		if d.enum != nil {
			code += "const ("
			for _, value := range d.enum {
				name := d.name + symbol(value)
				code += utils.S(`
				// {{.name}} enum const.
				{{.name}} {{.type}} = "{{.value}}"
				`, "name", name, "type", d.name, "value", value)
			}
			code += ")\n"
		}

	case objTypeStruct:
		code = utils.S(`
		{{.comment}}
		type {{.name}} struct {
		`, "name", d.name, "comment", d.comment())

		for _, prop := range d.props {
			tag := jsonTag(prop.originName, prop.optional && prop.typeName != "jsonvalue.Value")
			if d.name == "RuntimeCallArgument" && prop.name == "Value" {
				tag = "`json:\"value,omitzero\"`"
			}
			if d.name == "NetworkSetBlockedURLs" && prop.name == "Urls" {
				tag = "`json:\"urls,omitzero\"`"
			}

			code += utils.S(`
			{{.comment}}
			{{.name}} {{.type}} {{.tag}}
			`, "comment", prop.comment(), "name", prop.name, "type", fieldType(d, prop), "tag", tag)
		}

		code += "}\n"

		if d.command {
			method := d.domain.name + "." + d.originName
			if d.returnValue {
				code += utils.S(`
				// ProtoReq name.
				func (m {{.name}}) ProtoReq() string { return "{{.method}}" }

				// Call sends the request.
				func (m {{.name}}) Call(c Client) (*{{.name}}Result, error) {
					var res {{.name}}Result
					return &res, call(m.ProtoReq(), m, &res, c)
				}
				`, "name", d.name, "method", method)
			} else {
				code += utils.S(`
				// ProtoReq name.
				func (m {{.name}}) ProtoReq() string { return "{{.method}}" }

				// Call sends the request.
				func (m {{.name}}) Call(c Client) error {
					return call(m.ProtoReq(), m, nil, c)
				}
				`, "name", d.name, "method", method)
			}
		}

		if d.cdpType == cdpTypeEvents {
			code += utils.S(`
				// ProtoEvent name.
				func (evt {{.name}}) ProtoEvent() string {
					return "{{.event}}"
				}
			`, "name", d.name, "event", d.domain.name+"."+d.originName)
		}
	}

	return
}

// fieldType is the Go type of the field for prop in the struct d. Optional
// numbers, and optional booleans of commands, are pointers so that zero values
// can be sent.
func fieldType(d, prop *definition) string {
	if prop.optional {
		switch prop.typeName {
		case "bool":
			if d.command {
				return "*bool"
			}
		case "float64", "int":
			if !strings.Contains(prop.comment(), "(default: 0)") {
				return "*" + prop.typeName
			}
		}
	}
	return prop.typeName
}

func (d *definition) formatTests(decoders *decoders) string {
	method := d.domain.name + "." + d.originName
	switch d.cdpType {
	case cdpTypeCommands:
		if !d.command {
			return ""
		}
		call := "err := request.Call(c)"
		checkResult := ""
		client := "&Client{}"
		if d.returnValue {
			call = "result, err := request.Call(c)"
			checkResult = `if result == nil { t.Fatal("nil response") }`
			// Answer with the smallest result that has every required member.
			if response := decoders.minimalJSON(d.name + "Result"); response != "{}" {
				client = "&Client{ret: json.RawMessage(`" + response + "`)}"
			}
		}
		return utils.S(`
func Test{{.name}}(t *testing.T) {
 request := proto.{{.name}}{}
 if got := request.ProtoReq(); got != "{{.method}}" { t.Fatalf("request method = %q", got) }
 c := {{.client}}
 {{.call}}
 if err != nil { t.Fatal(err) }
 {{.checkResult}}
 if c.methodName != "{{.method}}" { t.Fatalf("called method = %q", c.methodName) }
 if !reflect.DeepEqual(c.params, request) { t.Fatalf("request parameters = %#v", c.params) }
}
`, "name", d.name, "method", method, "client", client, "call", call, "checkResult", checkResult)
	case cdpTypeEvents:
		return utils.S(`
func Test{{.name}}(t *testing.T) {
 if got := (proto.{{.name}}{}).ProtoEvent(); got != "{{.method}}" { t.Fatalf("event method = %q", got) }
}
`, "name", d.name, "method", method)
	}
	return ""
}
