package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// owned recognizes only this generator's current and historical headers.
func owned(data []byte) bool {
	header, _, _ := bytes.Cut(data, []byte("\n"))
	header = bytes.TrimSuffix(header, []byte("\r"))
	return string(header) == generatedHeader ||
		string(header) == "// This file is generated by \"./lib/proto/generate\""
}

// checkOutputs is read-only, including when the output directory is missing.
func checkOutputs(dir string, files map[string][]byte) error {
	var changed []string
	for name, expected := range files {
		path := filepath.Join(dir, name)
		info, err := os.Lstat(path)
		if errors.Is(err, os.ErrNotExist) {
			changed = append(changed, name+" (missing)")
			continue
		}
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			changed = append(changed, name+" (not a regular file)")
			continue
		}
		actual, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(actual, expected) {
			changed = append(changed, name+" (changed)")
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !entry.Type().IsRegular() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if _, expected := files[entry.Name()]; expected {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return err
		}
		if owned(data) {
			changed = append(changed, entry.Name()+" (obsolete)")
		}
	}
	if len(changed) != 0 {
		slices.Sort(changed)
		return fmt.Errorf("generated protocol bindings are stale:\n  %s\nregenerate with go run ./lib/proto/generate using the same browser", strings.Join(changed, "\n  "))
	}
	return nil
}

// replaceOutputs stages every output before replacing any file. Backups allow
// ordinary filesystem failures during replacement to restore the original set.
func replaceOutputs(dir string, files map[string][]byte) (err error) {
	return replaceOutputsWithRename(dir, files, os.Rename)
}

func replaceOutputsWithRename(dir string, files map[string][]byte, rename func(string, string) error) (err error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	previous := make(map[string]bool)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		info, err := os.Lstat(path)
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			if _, replacing := files[entry.Name()]; replacing {
				return fmt.Errorf("refusing to replace nonregular file %s", path)
			}
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if owned(data) {
			previous[entry.Name()] = true
		}
	}
	for name, data := range files {
		if name == schemaOutput || name == provenanceOutput || name == compatibilityOutput {
			path := filepath.Join(dir, name)
			if parent, err := os.Lstat(filepath.Dir(path)); err == nil && !parent.IsDir() {
				return fmt.Errorf("refusing non-directory metadata path %s", filepath.Dir(path))
			} else if err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			if info, err := os.Lstat(path); err == nil {
				if !info.Mode().IsRegular() {
					return fmt.Errorf("refusing to replace nonregular file %s", path)
				}
				previous[name] = true
			} else if !errors.Is(err, os.ErrNotExist) {
				return err
			}
			continue
		}
		if filepath.Base(name) != name || !strings.HasSuffix(name, ".go") || !owned(data) {
			return fmt.Errorf("invalid generated output %q", name)
		}
		if _, err := os.Lstat(filepath.Join(dir, name)); err == nil && !previous[name] {
			return fmt.Errorf("refusing to replace handwritten output %s", name)
		} else if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	stage, err := os.MkdirTemp(dir, ".proto-generate-")
	if err != nil {
		return err
	}
	keepBackups := false
	defer func() {
		if !keepBackups {
			err = errors.Join(err, os.RemoveAll(stage))
		}
	}()
	for name, data := range files {
		if err := os.MkdirAll(filepath.Dir(filepath.Join(stage, name)), 0o700); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(stage, name), data, 0o644); err != nil {
			return err
		}
	}
	backup := filepath.Join(stage, "backup")
	if err := os.Mkdir(backup, 0o700); err != nil {
		return err
	}
	var saved, installed []string
	defer func() {
		if err == nil {
			return
		}
		for _, name := range installed {
			err = errors.Join(err, os.Remove(filepath.Join(dir, name)))
		}
		for _, name := range saved {
			if restoreErr := rename(filepath.Join(backup, name), filepath.Join(dir, name)); restoreErr != nil {
				keepBackups = true
				err = errors.Join(err, fmt.Errorf("restore %s: %w; original retained in %s", name, restoreErr, backup))
			}
		}
	}()
	oldNames := make([]string, 0, len(previous))
	for name := range previous {
		oldNames = append(oldNames, name)
	}
	slices.Sort(oldNames)
	for _, name := range oldNames {
		if err := os.MkdirAll(filepath.Dir(filepath.Join(backup, name)), 0o700); err != nil {
			return err
		}
		if err := rename(filepath.Join(dir, name), filepath.Join(backup, name)); err != nil {
			return err
		}
		saved = append(saved, name)
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
			return err
		}
		if err := rename(filepath.Join(stage, name), filepath.Join(dir, name)); err != nil {
			return err
		}
		installed = append(installed, name)
	}
	return nil
}
