// Package main ...
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/rah-0/rod/lib/jsonvalue"
	"github.com/rah-0/rod/lib/utils"
)

func main() {
	if err := generate("lib/js/helper.js", "lib/js/helper.go"); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(source, output string) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	list, err := getList(string(data))
	if err != nil {
		return err
	}
	var out strings.Builder
	out.WriteString("// Code generated by \"lib/js/generate\"; DO NOT EDIT.\n\npackage js\n\n")
	for _, fn := range list.Arr() {
		name := fn.Get("name").Str()
		def := fn.Get("definition").Str()
		out.WriteString(utils.S(`
// {{.Name}} ...
var {{.Name}} = &Function{
 Name: "{{.name}}",
 Definition: {{.definition}},
 Dependencies: {{.dependencies}},
}
`, "Name", fnName(name), "name", name, "definition", utils.EscapeGoString(def), "dependencies", getDeps(def)))
	}
	code, err := format.Source([]byte(out.String()))
	if err != nil {
		return err
	}
	return writeOutput(output, code)
}

func writeOutput(path string, data []byte) error {
	file, err := os.CreateTemp(filepath.Dir(path), ".js-generate-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err := file.Write(data); err != nil {
		file.Close()
		return err
	}
	if err := file.Chmod(0o644); err != nil {
		file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), path)
}

var regDeps = regexp.MustCompile(`\Wfunctions.(\w+)`)

func getDeps(fn string) string {
	ms := regDeps.FindAllStringSubmatch(fn, -1)

	list := []string{}

	for _, m := range ms {
		list = append(list, fnName(m[1]))
	}

	return "[]*Function{" + strings.Join(list, ",") + "}"
}

func fnName(name string) string {
	return strings.ToUpper(name[0:1]) + name[1:]
}

func getList(source string) (jsonvalue.Value, error) {
	script := fmt.Sprintf(`
%s
const list = []
for (const name in functions) {
 const reg = new RegExp('^(async )?' + name)
 const definition = functions[name].toString().replace(reg, '$1function')
 list.push({name, definition})
}
console.log(JSON.stringify(list))
`, source)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "node", "-")
	cmd.Stdin = strings.NewReader(script)
	data, err := cmd.Output()
	if err != nil {
		return jsonvalue.Value{}, fmt.Errorf("serialize JavaScript helpers with Node.js: %w", err)
	}
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return jsonvalue.Value{}, err
	}
	return jsonvalue.New(value), nil
}
